apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artipie.fullname" . }}-server-config
  labels:
    {{- include "artipie.labels" . | nindent 4 }}
data:
  artipie.yml: |-
    meta:
      storage:
        type: fs
        path: /var/artipie/repo
      credentials:
        type: file
        path: _credentials.yaml
      layout: {{ .Values.artipie.layout }}
      base_url: {{ .Values.artipie.baseUrl }}
{{- if .Values.artipie.metrics.enabled -}}
      metrics:
        type: {{ .Values.artipie.metrics.type }}
        interval: {{ .Values.artipie.metrics.interval }}
{{- end }}
